--Ensures that values satisfy a specific condition.
CREATE TABLE EMPLOYEE_4(
EmployeId int PRIMARY KEY,
EmployeeName VARCHAR(100) NOT NULL,
DOJ DATETIME NOT NULL,
SALARY FLOAT CHECK(SALARY>=10000),
EMAIL VARCHAR(100) UNIQUE
)

INSERT INTO EMPLOYEE_4(EmployeId,EmployeeName,DOJ,SALARY,EMAIL)
VALUES(1,'TOMMY','2022-06-08',45000,'kerry234@gmail.com')

INSERT INTO EMPLOYEE_4(EmployeId,EmployeeName,DOJ,SALARY,EMAIL)
VALUES(2,'JACKSON2','2022-02-08',9999,'Jack234@gmail.com')