--SINGLE LINE COMMENT
--SELECT *FROM DimCustomer

SELECT  DISTINCT MiddleName FROM DimCustomer --THIS QUERY REMOVE DUPLICATE

/*MULTI LINE COMMENT*/

/*
SELECT  DISTINCT MiddleName FROM DimCustomer
SELECT  DISTINCT MiddleName FROM DimCustome
HII
HELLO
SELECT  DISTINCT MiddleName FROM DimCustomer
SELECT  DISTINCT MiddleName FROM DimCustomer
*/
SELECT  DISTINCT * FROM DimCustomer