--CURRENT DATETIME

SELECT GETDATE()

SELECT SYSDATETIME()

SELECT SYSUTCDATETIME()

SELECT DATEFROMPARTS(2025,12,04)

SELECT DATETIMEFROMPARTS(2025,11,04,6,45,15,0)

--DATE TIME PART 2

SELECT YEAR(GETDATE())
SELECT MONTH(GETDATE())
SELECT DAY(GETDATE())

SELECT BirthDate ,YEAR(BirthDate) FROM DimEmployee

SELECT BirthDate ,MONTH(BirthDate) FROM DimEmployee

SELECT BirthDate ,DAY(BirthDate) FROM DimEmployee

--DATEPART
SELECT DATEPART(YEAR,GETDATE())
SELECT DATEPART(MM,GETDATE())
SELECT DATEPART(DAY,GETDATE())
SELECT DATEPART(WEEK,GETDATE())
SELECT DATEPART(WEEKDAY,GETDATE())

--DATENAME
SELECT DATENAME(YEAR,GETDATE())
SELECT DATENAME(MM,GETDATE())
SELECT DATENAME(WEEKDAY,GETDATE())

--FORMATE
SELECT FORMAT(getdate(),'yy')

SELECT FORMAT(getdate(),'yyyy')

SELECT FORMAT(getdate(),'MM')

SELECT FORMAT(getdate(),'MMM')

SELECT FORMAT(getdate(),'dd')

SELECT FORMAT(getdate(),'ddd')

SELECT FORMAT(getdate(),'ddd-MMM-yyyy hh:mm:ss')

--DATETIME FUNCTION PART -3
 SELECT GETDATE()

 --YEAR +1 FUNCTION
 SELECT DATEADD(YEAR,1,GETDATE())
  SELECT DATEADD(MM,1,GETDATE())
   SELECT DATEADD(QUARTER,1,GETDATE())


--DIFFRENCE OF DATE YEAR
SELECT DATEDIFF(YEAR, DATEFROMPARTS(2010, 1, 1), GETDATE())
SELECT DATEDIFF(MM, DATEFROMPARTS(2010, 1, 1), GETDATE())
SELECT DATEDIFF(dd, DATEFROMPARTS(2010, 1, 1), GETDATE())


SELECT EOMONTH(GETDATE(), 0)

SELECT EOMONTH(GETDATE(), 1)

SELECT EOMONTH(GETDATE(), -1)


