 SELECT 'AB' + 'XY'

 SELECT 10 +30

 SELECT '10' + '30'
 
 SELECT '10' + 40

 SELECT 10 + 'X'

 SELECT CAST('10' AS INT)

SELECT CAST(ListPrice AS money) FROM DimProduct

SELECT CONVERT(INT, '10')

SELECT CONVERT(MONEY, LISTPRICE) FROM DimProduct
