--Ensures that all values in a column are different.

CREATE TABLE EMPLOYEE_3(
EmployeId int PRIMARY KEY,
EmployeeName VARCHAR(100) NOT NULL,
DOJ DATETIME NOT NULL,
SALARY FLOAT,
EMAIL VARCHAR(100) UNIQUE
)

INSERT INTO EMPLOYEE_3(EmployeId,EmployeeName,DOJ,SALARY,EMAIL)
VALUES(1,'KERRY','2022-06-08',45000,'kerry234@gmail.com')

INSERT INTO EMPLOYEE_3(EmployeId,EmployeeName,DOJ,SALARY,EMAIL)
VALUES(2,'JACKSON','2022-02-08',45000,'kerry234@gmail.com')

SELECT * FROM EMPLOYEE_3